music = {
    "high for this": "https://www.youtube.com/watch?v=sX9DgavXiN4",
    "what you need": "https://www.youtube.com/watch?v=PGCVhhUxnp8",
    "house of balloons / glass table girls": "https://www.youtube.com/watch?v=8ex38L8xtNI",
    "the morning": "https://www.youtube.com/watch?v=5TAko3RH0bk",
    "wicked games": "https://www.youtube.com/watch?v=o9PuAm7d0PA",
    "the party & the after party": "https://www.youtube.com/watch?v=yI-zb_aP0So",
    "coming down": "https://www.youtube.com/watch?v=WVg1mbxTkFo",
    "loft music": "https://www.youtube.com/watch?v=HOdNMwTNNhA",
    "the knowing": "https://www.youtube.com/watch?v=WsdmtOYtxNk",
    "twenty eight": "https://www.youtube.com/watch?v=2_ScGcuXZqc",
    "lonely star": "https://www.youtube.com/watch?v=pdH1kXzquQo",
    "life of the party": "https://www.youtube.com/watch?v=_bSXY75R3Wc",
    "thursday": "https://www.youtube.com/watch?v=0Suprl56Owg",
    "the zone (ft. drake)": "https://www.youtube.com/watch?v=YWIhwplfx4Q",
    "the birds part 1": "https://www.youtube.com/watch?v=t2_YyRBYZjM",
    "the birds part 2": "https://www.youtube.com/watch?v=9FE-Pwm2cyc",
    "gone": "https://www.youtube.com/watch?v=CqHKfscXS64",
    "rolling stone": "https://www.youtube.com/watch?v=fCPkgAIANys",
    "heaven or las vegas": "https://www.youtube.com/watch?v=dXbJ8-38yHw",
    "valerie": "https://www.youtube.com/watch?v=3asvFSESRVw",
    "d.d. (dirty diana cover)": "https://www.youtube.com/watch?v=FXT1oKrgq0o",
    "montreal": "https://www.youtube.com/watch?v=TV1r4m8c9SI",
    "outside": "https://www.youtube.com/watch?v=umvomiY7804",
    "xo / the host": "https://www.youtube.com/watch?v=6FFSCF0gXt0",
    "initiation": "https://www.youtube.com/watch?v=EDFEQyx7o4k",
    "same old song (ft. juicy j)": "https://www.youtube.com/watch?v=NID-2orTN8U",
    "the fall": "https://www.youtube.com/watch?v=YK9N-Xh32eE",
    "next": "https://www.youtube.com/watch?v=-iW1-BuJ_Hc",
    "echoes of silence": "https://www.youtube.com/watch?v=rtLBud9zPF0",
    "till dawn (here comes the sun)": "https://www.youtube.com/watch?v=PJaLS9C8W6I",

    # Kiss Land (2013)
    "professional": "https://www.youtube.com/watch?v=IkFdpL9meH8",
    "the town": "https://www.youtube.com/watch?v=0Ya3GXnvkzs",
    "adaptation": "https://www.youtube.com/watch?v=K4rQOS4jFCA",
    "love in the sky": "https://www.youtube.com/watch?v=QZjA4mD29I4",
    "belong to the world": "https://www.youtube.com/watch?v=lYO77zNhWl4",
    "live for (ft. drake)": "https://www.youtube.com/watch?v=GLr0usOC2_k",
    "wanderlust": "https://www.youtube.com/watch?v=r-YDJCK4krw",
    "kiss land": "https://www.youtube.com/watch?v=eN84vAqO9NY",
    "pretty": "https://www.youtube.com/watch?v=HxilwT1sKSo",
    "tears in the rain": "https://www.youtube.com/watch?v=f7GtAajflDc",
    "odd look (ft. kavinsky)": "https://www.youtube.com/watch?v=OSW2zeM3yLU",

    # Beauty Behind the Madness (2015)
    "often": "https://www.youtube.com/watch?v=2zF6ayMeq6o",
    "tell your friends": "https://www.youtube.com/watch?v=RZBJL8nclv0",
    "the hills": "https://www.youtube.com/watch?v=yzTuBuRdAyA",
    "can't feel my face": "https://www.youtube.com/watch?v=KEI4qSrkPAs",
    "in the night": "https://www.youtube.com/watch?v=5yJ4vGzo8OA",
    "acquainted": "https://www.youtube.com/watch?v=Jxp1K04s9lI",
    "dark times (ft. ed sheeran)": "https://www.youtube.com/watch?v=HsrP7nBH9Uc",
    "prisoner (ft. lana del rey)": "https://www.youtube.com/watch?v=7vOiQTcvVOw",
    "angel": "https://www.youtube.com/watch?v=ckqY3o0QW-c",
    "as you are": "https://www.youtube.com/watch?v=5rYuyQVZTeg",
    "shameless": "https://www.youtube.com/watch?v=Z7RR9qYzY_g",
    "earned it": "https://www.youtube.com/watch?v=H1tAjxJ-M6w",
    "losers": "https://www.youtube.com/watch?v=QTQvfHxDI8Y",

    # Starboy (2016)
    "starboy": "https://www.youtube.com/watch?v=34Na4j8AVgA",
    "party monster": "https://www.youtube.com/watch?v=NoNrdW7c34c",
    "false alarm": "https://www.youtube.com/watch?v=5QgjLM4t8MQ",
    "reminder": "https://www.youtube.com/watch?v=GynBNzwyaXE",
    "rockin'": "https://www.youtube.com/watch?v=xhrIV1L_3M4",
    "secrets": "https://www.youtube.com/watch?v=J26WlgBoZD0",
    "true colors": "https://www.youtube.com/watch?v=HPwcvo2wCIk",
    "stargirl interlude (ft. lana del rey)": "https://www.youtube.com/watch?v=Ipem3ISoBJU",
    "sidewalks (ft. kendrick lamar)": "https://www.youtube.com/watch?v=FqrG8V5gq3Q",
    "six feet under": "https://www.youtube.com/watch?v=cYVDinoNnlk",
    "love to lay": "https://www.youtube.com/watch?v=NDeQmt0UASo",
    "a lonely night": "https://www.youtube.com/watch?v=kvkmEV9E6rY",
    "attention": "https://www.youtube.com/watch?v=cRl7fy7CMlc",
    "ordinary life": "https://www.youtube.com/watch?v=mb_qYrxBPeE",
    "nothing without you": "https://www.youtube.com/watch?v=_7UXy5iQJvA",
    "all i know": "https://www.youtube.com/watch?v=3cpp-JuHyU0",
    "die for you": "https://www.youtube.com/watch?v=obg9s8fRJ5c",
    "i feel it coming": "https://www.youtube.com/watch?v=1G4isv_Fylg",

    # My Dear Melancholy (2018)
    "call out my name": "https://www.youtube.com/watch?v=RsEZmictANA",
    "try me": "https://www.youtube.com/watch?v=6UI62dj0UbM",
    "wasted times": "https://www.youtube.com/watch?v=w4IqgUcNzPA",
    "i was never there": "https://www.youtube.com/watch?v=xroXDGs7zjo",
    "hurt you": "https://www.youtube.com/watch?v=4sfjX6ZIKH8",
    "privilege": "https://www.youtube.com/watch?v=uApSuEbGviQ",

    # After Hours (2020)
    "alone again": "https://www.youtube.com/watch?v=Th67D1a248s",
    "too late": "https://www.youtube.com/watch?v=5w9vMIvEWZg",
    "hardest to love": "https://www.youtube.com/watch?v=2QkePJax-u4",
    "scared to live": "https://www.youtube.com/watch?v=LhZ0ai_dXTs",
    "snowchild": "https://www.youtube.com/watch?v=dgzRV7KODNU",
    "escape from la": "https://www.youtube.com/watch?v=rilF_mIUc8Y",
    "heartless": "https://www.youtube.com/watch?v=8y3f3Q8kZrE",
    "faith": "https://www.youtube.com/watch?v=1mwKMLOzYH4",
    "blinding lights": "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    "in your eyes": "https://www.youtube.com/watch?v=4JN74CvP45s",
    "save your tears": "https://www.youtube.com/watch?v=XXYlFuWEuKI",
    "repeat after me (interlude)": "https://www.youtube.com/watch?v=F8YeQIqsoxw",
    "after hours": "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    "until i bleed out": "https://www.youtube.com/watch?v=2yom59syq5s",

    # Dawn FM (2022)
    "gasoline": "https://www.youtube.com/watch?v=KKsm7Bx047A",
    "how do i make you love me?": "https://www.youtube.com/watch?v=GgeOvL9NcXs",
    "take my breath": "https://www.youtube.com/watch?v=2iE5hofFvYo",
    "sacrifice": "https://www.youtube.com/watch?v=tF_Ud5mlMwE",
    "a tale by quincy": "https://www.youtube.com/watch?v=EWxDs-OwKvQ",
    "out of time": "https://www.youtube.com/watch?v=Hn9UdaAkGs8",
    "here we go... again (ft. tyler, the creator)": "https://www.youtube.com/watch?v=X5Pes1-tTAc",
    "best friends": "https://www.youtube.com/watch?v=kTs0SotQNVM",
    "is there someone else?": "https://www.youtube.com/watch?v=VKlEtbQiyPs",
    "starry eyes": "https://www.youtube.com/watch?v=19hYr67Fk8k",
    "every angel is terrifying": "https://www.youtube.com/watch?v=BBDHX_JGVOY",
    "don’t break my heart": "https://www.youtube.com/watch?v=1LU_Self0D4",
    "i heard you’re married (ft. lil wayne)": "https://www.youtube.com/watch?v=LfY3dHd-rCM",
    "less than zero": "https://www.youtube.com/watch?v=K3_M5rTBARw",
    "phantom regret by jim": "https://www.youtube.com/watch?v=k1UvH5QvG7A",

    # Hurry Up Tomorrow (2025)
    "wake me up (feat. justice)": "https://www.youtube.com/watch?v=OwQW1DorPck",
    "cry for me": "https://www.youtube.com/watch?v=x8xIa3VM7e",
    "i can't fucking sing": "",
    "são paulo (with anitta)": "https://www.youtube.com/watch?v=GpYSqCondFE",
    "until we're skin & bones": "",
    "baptized in fear": "",
    "open hearts": "https://www.youtube.com/watch?v=Bn-3ICGjz0U",
    "opening night": "",
    "reflections laughing (feat. travis scott, florence and the machine)": "https://www.youtube.com/watch?v=ClarIaErkkE",
    "enjoy the show (feat. future)": "https://www.youtube.com/watch?v=FachosDZTfE",
    "given up on me": "",
    "i can't wait to get there": "",
    "timeless (feat. playboi carti)": "https://www.youtube.com/watch?v=8m9F6CKFxRY",
    "niagara falls": "",
    "take me back to la": "",
    "big sleep (feat. giorgio moroder)": "",
    "give me mercy": "",
    "drive": "",
    "the abyss (feat. lana del rey)": "https://www.youtube.com/watch?v=-ePa_rb8syk",
    "red terror": "",
    "without a warning": "",
    "hurry up tomorrow": "",
    "runaway": "",
    "society": "",
    "closing night (feat. swedish house mafia)": "",
    "cry for me (music video)": "https://www.youtube.com/watch?v=24nbzJEOjBw",
    "são paulo (music video)": "https://www.youtube.com/watch?v=Q7uWy_ZcGAQ",
    "open hearts (music video)": "https://www.youtube.com/watch?v=FalkXjW27l4",
    "timeless (music video)": "https://www.youtube.com/watch?v=GAkd2M0u-uI",
    "red terror (music video)": "https://www.youtube.com/watch?v=8rBBlYIse_8"
}
